// <auto-generated />
using System;
using be.Domain.Enums;
using be.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace mini4rum.Migrations
{
    [DbContext(typeof(WriteContext))]
    [Migration("20260331141610_seed_admin")]
    partial class seed_admin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "image_enum", new[] { "after", "before", "normal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "noti_action_enum", new[] { "react", "comment", "follow" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "noti_target_enum", new[] { "post", "user" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "react_enum", new[] { "like", "dislike" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "role_enum", new[] { "admin", "user" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "status_account_enum", new[] { "active", "banned", "deleted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "status_post_enum", new[] { "active", "deleted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "status_report_post_enum", new[] { "pending", "resolved", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "third_party_login_enum", new[] { "google" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "type_conversation_enum", new[] { "single", "group" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum", "type_message_enum", new[] { "text", "image", "video", "system" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("min.Models.Account", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CreatAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsThirdParty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_third_party");

                    b.Property<string>("Mail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mail");

                    b.Property<string>("Pass")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pass");

                    b.Property<RoleEnum>("Role")
                        .HasColumnType("enum.role_enum")
                        .HasColumnName("role");

                    b.Property<short>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("score");

                    b.Property<StatusAccountEnum>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum.status_account_enum")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::enum.status_account_enum");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex(new[] { "Mail" }, "uq_mail")
                        .IsUnique()
                        .HasFilter("status = 'active'");

                    b.ToTable("accounts", "auth", t =>
                        {
                            t.HasCheckConstraint("ck_mail_format", "mail ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'");

                            t.HasCheckConstraint("ck_pass_lenght", "char_length(pass) > 5");

                            t.HasCheckConstraint("ck_pass_or_third_party", "is_third_party OR (pass IS NOT NULL AND char_length(pass) > 5)");
                        });
                });

            modelBuilder.Entity("min.Models.AdminDelAccountLog", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short?>("AdminId")
                        .HasColumnType("smallint")
                        .HasColumnName("admin_id");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<short>("TargetId")
                        .HasColumnType("smallint")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_del_account_logs");

                    b.HasIndex("AdminId");

                    b.HasIndex("TargetId", "AdminId")
                        .IsUnique()
                        .HasDatabaseName("uq_target_admin");

                    b.ToTable("admin_del_account_logs", "logging", t =>
                        {
                            t.HasCheckConstraint("ck_admin_del_account_log_fk_positive", "target_id > 0 AND (admin_id >= 0 OR admin_id IS NULL)");
                        });
                });

            modelBuilder.Entity("min.Models.AdminDelPostLog", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short?>("AdminId")
                        .HasColumnType("smallint")
                        .HasColumnName("admin_id");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<short>("PostId")
                        .HasColumnType("smallint")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_del_post_logs");

                    b.HasIndex("AdminId");

                    b.HasIndex("PostId", "AdminId")
                        .IsUnique()
                        .HasDatabaseName("uq_post_admin");

                    b.ToTable("admin_del_post_logs", "logging", t =>
                        {
                            t.HasCheckConstraint("ck_admin_del_post_log_fk_positive", "post_id > 0 AND (admin_id >= 0 OR admin_id IS NULL)");
                        });
                });

            modelBuilder.Entity("min.Models.AdminResolveReportLog", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("AdminId")
                        .HasColumnType("smallint")
                        .HasColumnName("admin_id");

                    b.Property<short>("ReportId")
                        .HasColumnType("smallint")
                        .HasColumnName("report_id");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_admin_resolve_report_log");

                    b.HasIndex("AdminId");

                    b.HasIndex("ReportId", "AdminId")
                        .IsUnique()
                        .HasDatabaseName("uq_report_admin");

                    b.ToTable("admin_resolve_report_log", "logging", t =>
                        {
                            t.HasCheckConstraint("ck_admin_resolve_report_log_fk_positive", "report_id > 0 AND admin_id > 0");
                        });
                });

            modelBuilder.Entity("min.Models.Comment", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<short>("PostId")
                        .HasColumnType("smallint")
                        .HasColumnName("post_id");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("comments", "engagement", t =>
                        {
                            t.HasCheckConstraint("ck_content_length", "char_length(content) >= 1");
                        });
                });

            modelBuilder.Entity("min.Models.ConversationUser", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("ConversationId")
                        .HasColumnType("smallint")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("UnreadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("unread_count");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_conversation_users");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId", "ConversationId")
                        .IsUnique()
                        .HasDatabaseName("ux_conversation_participants_conversation_id_user_id");

                    b.ToTable("conversation_participants", "chat");
                });

            modelBuilder.Entity("min.Models.Conversations", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CreatorId")
                        .HasColumnType("smallint")
                        .HasColumnName("creator_id");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<string>("KeyParticipants")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("key_participant");

                    b.Property<string>("LastMessage")
                        .HasMaxLength(70)
                        .HasColumnType("text")
                        .HasColumnName("last_message");

                    b.Property<TypeConversationEnum>("Type")
                        .HasColumnType("enum.type_conversation_enum")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversation");

                    b.HasIndex("KeyParticipants")
                        .IsUnique()
                        .HasDatabaseName("ix_conversations_key_participants");

                    b.ToTable("conversations", "chat", t =>
                        {
                            t.HasCheckConstraint("ck_last_message_length", "char_length(last_message) <= 70");

                            t.HasCheckConstraint("ck_single_conversation_key_participants", "type != 'single' OR (type = 'single' AND key_participant IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("min.Models.Feedback", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_feedback");

                    b.HasIndex("UserId");

                    b.ToTable("feedbacks", "support", t =>
                        {
                            t.HasCheckConstraint("ck_content_length", "char_length(content) >= 20");
                        });
                });

            modelBuilder.Entity("min.Models.Follow", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("FolloweeId")
                        .HasColumnType("smallint")
                        .HasColumnName("followee_id");

                    b.Property<short>("FollowerId")
                        .HasColumnType("smallint")
                        .HasColumnName("follower_id");

                    b.HasKey("Id")
                        .HasName("pk_follow");

                    b.HasIndex("FolloweeId");

                    b.HasIndex("FollowerId", "FolloweeId")
                        .IsUnique()
                        .HasDatabaseName("uq_follows_follower_followee");

                    b.ToTable("follows", "engagement", t =>
                        {
                            t.HasCheckConstraint("ck_follow_no_self", "\"follower_id\" <> \"followee_id\"");
                        });
                });

            modelBuilder.Entity("min.Models.Message", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<short>("ConversationId")
                        .HasColumnType("smallint")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("SenderId")
                        .HasColumnType("smallint")
                        .HasColumnName("sender_id");

                    b.Property<TypeMessageEnum>("Type")
                        .HasColumnType("enum.type_message_enum")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("messages", "chat", t =>
                        {
                            t.HasCheckConstraint("ck_message_content_length", "char_length(content) <= 5000");
                        });
                });

            modelBuilder.Entity("min.Models.MessageRead", b =>
                {
                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.Property<short>("MessageId")
                        .HasColumnType("smallint")
                        .HasColumnName("message_id");

                    b.Property<short>("ConversationId")
                        .HasColumnType("smallint")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("ReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "MessageId")
                        .HasName("pk_message_reads");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessageId");

                    b.ToTable("message_reads", "chat");
                });

            modelBuilder.Entity("min.Models.NotiCmt", b =>
                {
                    b.Property<short>("NotiId")
                        .HasColumnType("smallint")
                        .HasColumnName("noti_id");

                    b.Property<short>("CmtId")
                        .HasColumnType("smallint")
                        .HasColumnName("cmt_id");

                    b.Property<short>("PostId")
                        .HasColumnType("smallint")
                        .HasColumnName("post_id");

                    b.Property<string>("Preview")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("preview");

                    b.HasKey("NotiId")
                        .HasName("pk_cmts");

                    b.HasIndex("CmtId");

                    b.HasIndex("PostId");

                    b.ToTable("noti_cmts", "notifications");
                });

            modelBuilder.Entity("min.Models.NotiReactPost", b =>
                {
                    b.Property<short>("NotiId")
                        .HasColumnType("smallint")
                        .HasColumnName("noti_id");

                    b.Property<short>("PostId")
                        .HasColumnType("smallint")
                        .HasColumnName("post_id");

                    b.Property<string>("PreviewContent")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("preview_content");

                    b.Property<ReactEnum>("Type")
                        .HasColumnType("enum.react_enum")
                        .HasColumnName("type");

                    b.HasKey("NotiId")
                        .HasName("pk_noti_reacts");

                    b.HasIndex("PostId");

                    b.ToTable("noti_reacts", "notifications");
                });

            modelBuilder.Entity("min.Models.Notifications", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<NotiActionEnum>("Action")
                        .HasColumnType("enum.noti_action_enum")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<short>("ReciverId")
                        .HasColumnType("smallint")
                        .HasColumnName("reciver_id");

                    b.Property<short>("SenderId")
                        .HasColumnType("smallint")
                        .HasColumnName("sender_id");

                    b.Property<NotiTargetEnum>("Target")
                        .HasColumnType("enum.noti_target_enum")
                        .HasColumnName("target");

                    b.Property<Guid?>("ThumbnailNoti")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_noti");

                    b.HasKey("Id")
                        .HasName("pk_notifacations");

                    b.HasIndex("ReciverId");

                    b.HasIndex("SenderId");

                    b.ToTable("notifications", "notifications");
                });

            modelBuilder.Entity("min.Models.Post", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creat_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<short>("ScoreReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("score_report");

                    b.Property<short>("ScoreTrend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("score");

                    b.Property<StatusPostEnum>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum.status_post_enum")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::enum.status_post_enum");

                    b.Property<short>("TotalComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("total_comment");

                    b.Property<short>("TotalDislike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("total_dislike");

                    b.Property<short>("TotalLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("total_like");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_post");

                    b.HasIndex("UserId");

                    b.ToTable("posts", "content");
                });

            modelBuilder.Entity("min.Models.PostImage", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short?>("GroupId")
                        .HasColumnType("smallint")
                        .HasColumnName("group_id");

                    b.Property<Guid>("Image")
                        .HasColumnType("uuid")
                        .HasColumnName("image");

                    b.Property<short>("PostId")
                        .HasColumnType("smallint")
                        .HasColumnName("post_id");

                    b.Property<ImageEnum>("Type")
                        .HasColumnType("enum.image_enum")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("post_images", "content");
                });

            modelBuilder.Entity("min.Models.Question", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex(new[] { "Content" }, "uq_content")
                        .IsUnique();

                    b.ToTable("questions", "questions");
                });

            modelBuilder.Entity("min.Models.QuestionPlaylist", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("CurrentIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("current_index");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("jsonb")
                        .HasColumnName("questions");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_question_playlists");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_question_playlists_user_id");

                    b.ToTable("question_playlists", "questions");
                });

            modelBuilder.Entity("min.Models.ReactPost", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CreatAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creat_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("PostId")
                        .HasColumnType("smallint")
                        .HasColumnName("post_id");

                    b.Property<ReactEnum>("Type")
                        .HasColumnType("enum.react_enum")
                        .HasColumnName("type");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_react");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique()
                        .HasDatabaseName("uq_react_user_post");

                    b.ToTable("react_posts", "engagement");
                });

            modelBuilder.Entity("min.Models.ReasonReportPost", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("Code")
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_report");

                    b.HasIndex(new[] { "Code" }, "uq_code")
                        .IsUnique();

                    b.ToTable("reason_report_post", "engagement", t =>
                        {
                            t.HasCheckConstraint("ck_check_code", "code >= 0");
                        });
                });

            modelBuilder.Entity("min.Models.ThirdPartyLogin", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("AccountId")
                        .HasColumnType("smallint")
                        .HasColumnName("account_id");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mail");

                    b.Property<ThirdPartyLoginEnum>("Provider")
                        .HasColumnType("enum.third_party_login_enum")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_id");

                    b.HasKey("Id")
                        .HasName("pk_third_party_login");

                    b.HasIndex("AccountId");

                    b.HasIndex("Provider", "ProviderId")
                        .IsUnique()
                        .HasDatabaseName("uq_provider_provider_id");

                    b.ToTable("third_party_logins", "auth", t =>
                        {
                            t.HasCheckConstraint("ck_mail_format", "mail ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'");
                        });
                });

            modelBuilder.Entity("min.Models.Token", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("AccountId")
                        .HasColumnType("smallint")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token");

                    b.HasKey("Id")
                        .HasName("pk_tokens");

                    b.HasIndex("AccountId");

                    b.ToTable("tokens", "auth");
                });

            modelBuilder.Entity("min.Models.User", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("AccountId")
                        .HasColumnType("smallint")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("Avatar")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar");

                    b.Property<string>("Bio")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("bio");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<short>("TotalFollower")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("total_follower");

                    b.Property<short>("TotalFollowing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("total_following");

                    b.Property<short>("TotalPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("total_post");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "uq_userid")
                        .IsUnique();

                    b.ToTable("users", "user", t =>
                        {
                            t.HasCheckConstraint("ck_user_id_type", "char_length(user_id) BETWEEN 3 AND 50 AND user_id ~ '^[A-Za-z0-9_]+$'");

                            t.HasCheckConstraint("ck_user_name_type", "char_length(name) BETWEEN 3 AND 50 AND name !~ '^\\s' AND name !~ '\\s$' AND name !~ '\\s{2,}'");

                            t.HasCheckConstraint("ck_users_total_non_negative", "total_follower >= 0 AND total_following >= 0 AND total_post >= 0");
                        });
                });

            modelBuilder.Entity("min.Models.UserQuestionLog", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("QuestionId")
                        .HasColumnType("smallint")
                        .HasColumnName("question_id");

                    b.Property<DateTimeOffset>("ShowAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("show_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("TotalQuestions")
                        .HasColumnType("smallint")
                        .HasColumnName("total_questions");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_question_logs");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("user_question_logs", "logging");
                });

            modelBuilder.Entity("min.Models.UserReportPost", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OtherReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("other_reason");

                    b.Property<short>("ReportCode")
                        .HasColumnType("smallint")
                        .HasColumnName("report_code");

                    b.Property<short>("ReportedPost")
                        .HasColumnType("smallint")
                        .HasColumnName("reported_post");

                    b.Property<short>("ReporterId")
                        .HasColumnType("smallint")
                        .HasColumnName("reporter_id");

                    b.Property<StatusReportPostEnum>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum.status_report_post_enum")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::enum.status_report_post_enum");

                    b.HasKey("Id")
                        .HasName("pk_user_reports");

                    b.HasIndex("ReportCode");

                    b.HasIndex("ReportedPost");

                    b.HasIndex("ReporterId", "ReportedPost", "ReportCode")
                        .IsUnique()
                        .HasDatabaseName("uq_user_report_once_per_reason");

                    b.ToTable("user_report_posts", "engagement");
                });

            modelBuilder.Entity("min.Models.UseridChangeLog", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NewUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("new_userid");

                    b.Property<string>("OldUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("old_userid");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_userid_change_log");

                    b.HasIndex("UserId");

                    b.ToTable("userid_change_log", "logging", t =>
                        {
                            t.HasCheckConstraint("ck_new_userid_type", "char_length(new_userid) BETWEEN 3 AND 50 AND new_userid ~ '^[A-Za-z0-9_]+$'");

                            t.HasCheckConstraint("ck_old_userid_type", "char_length(old_userid) BETWEEN 3 AND 50 AND old_userid ~ '^[A-Za-z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("min.Models.UsernameChangeLog", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("ChangeAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("change_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NewUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("new_username");

                    b.Property<string>("OldUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("old_username");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_username_change_log");

                    b.HasIndex("UserId");

                    b.ToTable("username_change_log", "logging", t =>
                        {
                            t.HasCheckConstraint("ck_new_username_type", "char_length(new_username) BETWEEN 3 AND 50 AND new_username !~ '^\\s' AND new_username !~ '\\s$' AND new_username !~ '\\s{2,}'");

                            t.HasCheckConstraint("ck_old_username_type", "char_length(old_username) BETWEEN 3 AND 50 AND old_username !~ '^\\s' AND old_username !~ '\\s$' AND old_username !~ '\\s{2,}'");
                        });
                });

            modelBuilder.Entity("min.Models.AdminDelAccountLog", b =>
                {
                    b.HasOne("min.Models.Account", "AccountNavi")
                        .WithMany("AdminDelAccountLogsNavi")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_accounts_admin_del_account_logs");

                    b.HasOne("min.Models.User", "TargetIdNavi")
                        .WithMany("TargetAdminDelAccountLogsNavi")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_target_del_account_navi");

                    b.Navigation("AccountNavi");

                    b.Navigation("TargetIdNavi");
                });

            modelBuilder.Entity("min.Models.AdminDelPostLog", b =>
                {
                    b.HasOne("min.Models.Account", "AccountNavi")
                        .WithMany("AdminDelPostLogsNavi")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_accounts_admin_del_post_logs");

                    b.HasOne("min.Models.Post", "PostNavi")
                        .WithMany("AdminDelPostLogNavi")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_post_del_post_navi");

                    b.Navigation("AccountNavi");

                    b.Navigation("PostNavi");
                });

            modelBuilder.Entity("min.Models.AdminResolveReportLog", b =>
                {
                    b.HasOne("min.Models.Account", "AccountNavi")
                        .WithMany("AdminResolveReportLogsNavi")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_resolve_report_log_user");

                    b.HasOne("min.Models.UserReportPost", "ReportNavi")
                        .WithMany("AdminResolveReportLogsNavi")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_resolve_report_log_report");

                    b.Navigation("AccountNavi");

                    b.Navigation("ReportNavi");
                });

            modelBuilder.Entity("min.Models.Comment", b =>
                {
                    b.HasOne("min.Models.Post", "PostNavi")
                        .WithMany("CommentNavi")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_post");

                    b.HasOne("min.Models.User", "UserNavi")
                        .WithMany("CommentNavi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_user");

                    b.Navigation("PostNavi");

                    b.Navigation("UserNavi");
                });

            modelBuilder.Entity("min.Models.ConversationUser", b =>
                {
                    b.HasOne("min.Models.Conversations", "ConversationsNavi")
                        .WithMany("ConversationUserNavi")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_participants_conversation_id");

                    b.HasOne("min.Models.User", "UsersNavi")
                        .WithMany("ConversationUsersNavi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_participants_user_id");

                    b.Navigation("ConversationsNavi");

                    b.Navigation("UsersNavi");
                });

            modelBuilder.Entity("min.Models.Feedback", b =>
                {
                    b.HasOne("min.Models.User", "UserNavi")
                        .WithMany("FeedbackNavi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_user");

                    b.Navigation("UserNavi");
                });

            modelBuilder.Entity("min.Models.Follow", b =>
                {
                    b.HasOne("min.Models.User", "FolloweeNavi")
                        .WithMany("FollowersNavi")
                        .HasForeignKey("FolloweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_following_user");

                    b.HasOne("min.Models.User", "FollowerNavi")
                        .WithMany("FollowingNavi")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follwer_user");

                    b.Navigation("FolloweeNavi");

                    b.Navigation("FollowerNavi");
                });

            modelBuilder.Entity("min.Models.Message", b =>
                {
                    b.HasOne("min.Models.Conversations", "ConversationNavi")
                        .WithMany("MessagesNavi")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversation_id");

                    b.HasOne("min.Models.User", "SenderNavi")
                        .WithMany("MessagesNavi")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_sender_id");

                    b.Navigation("ConversationNavi");

                    b.Navigation("SenderNavi");
                });

            modelBuilder.Entity("min.Models.MessageRead", b =>
                {
                    b.HasOne("min.Models.Conversations", "ConversationNavi")
                        .WithMany("MessageReadNavi")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readmessage_conversation");

                    b.HasOne("min.Models.Message", "MessageNavi")
                        .WithMany("MessageReadsNavi")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readmessage_message");

                    b.HasOne("min.Models.User", "UserNavi")
                        .WithMany("MessageReadsNavi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messagereads_user");

                    b.Navigation("ConversationNavi");

                    b.Navigation("MessageNavi");

                    b.Navigation("UserNavi");
                });

            modelBuilder.Entity("min.Models.NotiCmt", b =>
                {
                    b.HasOne("min.Models.Comment", "CmtNavi")
                        .WithMany("NotiCmtNavi")
                        .HasForeignKey("CmtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_noticmt_cmt");

                    b.HasOne("min.Models.Notifications", "NotiNavi")
                        .WithOne("NotiCmtNavi")
                        .HasForeignKey("min.Models.NotiCmt", "NotiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_noti");

                    b.HasOne("min.Models.Post", "PostNavi")
                        .WithMany("NotiCmtNavi")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_noticmt_post");

                    b.Navigation("CmtNavi");

                    b.Navigation("NotiNavi");

                    b.Navigation("PostNavi");
                });

            modelBuilder.Entity("min.Models.NotiReactPost", b =>
                {
                    b.HasOne("min.Models.Notifications", "NotiNavi")
                        .WithOne("NotiReactNavi")
                        .HasForeignKey("min.Models.NotiReactPost", "NotiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_noti");

                    b.HasOne("min.Models.Post", "PostNavi")
                        .WithMany("NotiReactPostNavi")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notireactpost_post");

                    b.Navigation("NotiNavi");

                    b.Navigation("PostNavi");
                });

            modelBuilder.Entity("min.Models.Notifications", b =>
                {
                    b.HasOne("min.Models.User", "ReciverNavi")
                        .WithMany("ReciverNotiNavi")
                        .HasForeignKey("ReciverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_noti_user_receiver");

                    b.HasOne("min.Models.User", "SenderNavi")
                        .WithMany("SenderNotiNavi")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_noti_user_sender");

                    b.Navigation("ReciverNavi");

                    b.Navigation("SenderNavi");
                });

            modelBuilder.Entity("min.Models.Post", b =>
                {
                    b.HasOne("min.Models.User", "UserNavi")
                        .WithMany("PostNavi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_user");

                    b.Navigation("UserNavi");
                });

            modelBuilder.Entity("min.Models.PostImage", b =>
                {
                    b.HasOne("min.Models.Post", "PostNavi")
                        .WithMany("PostImageNavi")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_image_post");

                    b.Navigation("PostNavi");
                });

            modelBuilder.Entity("min.Models.QuestionPlaylist", b =>
                {
                    b.HasOne("min.Models.User", "UserNavi")
                        .WithOne("QuestionPlaylistNavi")
                        .HasForeignKey("min.Models.QuestionPlaylist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_users");

                    b.Navigation("UserNavi");
                });

            modelBuilder.Entity("min.Models.ReactPost", b =>
                {
                    b.HasOne("min.Models.Post", "PostNavi")
                        .WithMany("ReacPostNavi")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_react_post");

                    b.HasOne("min.Models.User", "UserNavi")
                        .WithMany("ReactNavi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_react_user");

                    b.Navigation("PostNavi");

                    b.Navigation("UserNavi");
                });

            modelBuilder.Entity("min.Models.ThirdPartyLogin", b =>
                {
                    b.HasOne("min.Models.Account", "AccountNavi")
                        .WithMany("ThirdPartyLoginsNavi")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_third_party_login_account");

                    b.Navigation("AccountNavi");
                });

            modelBuilder.Entity("min.Models.Token", b =>
                {
                    b.HasOne("min.Models.Account", "AccountNavi")
                        .WithMany("TokensNavi")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_token");

                    b.Navigation("AccountNavi");
                });

            modelBuilder.Entity("min.Models.User", b =>
                {
                    b.HasOne("min.Models.Account", "AccountNavi")
                        .WithOne("UserNavi")
                        .HasForeignKey("min.Models.User", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_accounts");

                    b.Navigation("AccountNavi");
                });

            modelBuilder.Entity("min.Models.UserQuestionLog", b =>
                {
                    b.HasOne("min.Models.Question", "QuestionNavi")
                        .WithMany("UserQuestionLogNavi")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_question_logs_questions");

                    b.HasOne("min.Models.User", "UserNavi")
                        .WithMany("UserQuestionLogsNavi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_question_logs_users");

                    b.Navigation("QuestionNavi");

                    b.Navigation("UserNavi");
                });

            modelBuilder.Entity("min.Models.UserReportPost", b =>
                {
                    b.HasOne("min.Models.ReasonReportPost", "ReasonReportPostNavi")
                        .WithMany("UserReportsNavi")
                        .HasForeignKey("ReportCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reports_report_reasons");

                    b.HasOne("min.Models.Post", "PostNavi")
                        .WithMany("UserReportNavi")
                        .HasForeignKey("ReportedPost")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reports_posts");

                    b.HasOne("min.Models.User", "UserNavi")
                        .WithMany("UserReportNavi")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reports_users");

                    b.Navigation("PostNavi");

                    b.Navigation("ReasonReportPostNavi");

                    b.Navigation("UserNavi");
                });

            modelBuilder.Entity("min.Models.UseridChangeLog", b =>
                {
                    b.HasOne("min.Models.User", "UserNavi")
                        .WithMany("UseridChangeLogNavi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_userid_change_log_user");

                    b.Navigation("UserNavi");
                });

            modelBuilder.Entity("min.Models.UsernameChangeLog", b =>
                {
                    b.HasOne("min.Models.User", "UserNavi")
                        .WithMany("UsernameChangeLogNavi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_username_change_log_user");

                    b.Navigation("UserNavi");
                });

            modelBuilder.Entity("min.Models.Account", b =>
                {
                    b.Navigation("AdminDelAccountLogsNavi");

                    b.Navigation("AdminDelPostLogsNavi");

                    b.Navigation("AdminResolveReportLogsNavi");

                    b.Navigation("ThirdPartyLoginsNavi");

                    b.Navigation("TokensNavi");

                    b.Navigation("UserNavi")
                        .IsRequired();
                });

            modelBuilder.Entity("min.Models.Comment", b =>
                {
                    b.Navigation("NotiCmtNavi");
                });

            modelBuilder.Entity("min.Models.Conversations", b =>
                {
                    b.Navigation("ConversationUserNavi");

                    b.Navigation("MessageReadNavi");

                    b.Navigation("MessagesNavi");
                });

            modelBuilder.Entity("min.Models.Message", b =>
                {
                    b.Navigation("MessageReadsNavi");
                });

            modelBuilder.Entity("min.Models.Notifications", b =>
                {
                    b.Navigation("NotiCmtNavi")
                        .IsRequired();

                    b.Navigation("NotiReactNavi")
                        .IsRequired();
                });

            modelBuilder.Entity("min.Models.Post", b =>
                {
                    b.Navigation("AdminDelPostLogNavi");

                    b.Navigation("CommentNavi");

                    b.Navigation("NotiCmtNavi");

                    b.Navigation("NotiReactPostNavi");

                    b.Navigation("PostImageNavi");

                    b.Navigation("ReacPostNavi");

                    b.Navigation("UserReportNavi");
                });

            modelBuilder.Entity("min.Models.Question", b =>
                {
                    b.Navigation("UserQuestionLogNavi");
                });

            modelBuilder.Entity("min.Models.ReasonReportPost", b =>
                {
                    b.Navigation("UserReportsNavi");
                });

            modelBuilder.Entity("min.Models.User", b =>
                {
                    b.Navigation("CommentNavi");

                    b.Navigation("ConversationUsersNavi");

                    b.Navigation("FeedbackNavi");

                    b.Navigation("FollowersNavi");

                    b.Navigation("FollowingNavi");

                    b.Navigation("MessageReadsNavi");

                    b.Navigation("MessagesNavi");

                    b.Navigation("PostNavi");

                    b.Navigation("QuestionPlaylistNavi")
                        .IsRequired();

                    b.Navigation("ReactNavi");

                    b.Navigation("ReciverNotiNavi");

                    b.Navigation("SenderNotiNavi");

                    b.Navigation("TargetAdminDelAccountLogsNavi");

                    b.Navigation("UserQuestionLogsNavi");

                    b.Navigation("UserReportNavi");

                    b.Navigation("UseridChangeLogNavi");

                    b.Navigation("UsernameChangeLogNavi");
                });

            modelBuilder.Entity("min.Models.UserReportPost", b =>
                {
                    b.Navigation("AdminResolveReportLogsNavi");
                });
#pragma warning restore 612, 618
        }
    }
}
